### ISSUE TITLE
能否加上更新chin_ip.txt user.rule的菜单

### ISSUE THREAD

**Issue by ghost** [HMBSbige/shadowsocksr-csharp#1]
如果能加上，更加方便了。

**Comment by HMBSbige** [comment]
chn_ip.txt有这个意向
但是user.rule本来就是为了用户自定义，没有增加这个的必要吧

**Comment by ghost** [comment]
普通用户会在现成的规则上做简单的自定义，

**Comment by ghost** [comment]
大部分用户是拿来主义，小部分是现成的基础上简单自定义，个别用户才是你说的情况

**Comment by HMBSbige** [comment]
所以还是没懂，凭借什么生成 user.rule
本来这文件就是用来根据各自的不同情况来自定义的
